site_name: Exfilter
theme:
  name: material
  logo: 
  favicon: images/favicon.ico
  include_homepage_in_sidebar: false
  palette:
    scheme: default
    primary: grey
    accent: blue
  features:
    - navigation.tabs
    - navigation.tracking
    - navigation.indexes
copyright: |
  &copy; Copyright Replicated. All rights reserved. <br />
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/replicatedhq/exfilter
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/replicatedhq
markdown_extensions:
  - admonition
  - attr_list
nav:
  - 'Getting Started':
    - 'Overview': 'getting-started/overview.md'
    - 'Use Cases': 'getting-started/use-cases.md'
    - 'Quickstart': 'getting-started/quickstart.md'

  - 'Docs':
    - 'Installing': 'docs/installing.md'
    - 'How it works': 'docs/how-it-works.md'
    - 'Contributing': 'docs/contributing.md'
    